export const indonesiaAddressOptions = [
  { city: "Jakarta Pusat", province: "DKI Jakarta", postalCode: "10270" },
  { city: "Jakarta Selatan", province: "DKI Jakarta", postalCode: "12110" },
  { city: "Jakarta Barat", province: "DKI Jakarta", postalCode: "11110" },
  { city: "Jakarta Timur", province: "DKI Jakarta", postalCode: "13110" },
  { city: "Jakarta Utara", province: "DKI Jakarta", postalCode: "14110" },
  { city: "Kota Bekasi", province: "Jawa Barat", postalCode: "17111" },
  { city: "Kabupaten Bekasi", province: "Jawa Barat", postalCode: "17530" },
  { city: "Kota Bogor", province: "Jawa Barat", postalCode: "16111" },
  { city: "Kabupaten Bogor", province: "Jawa Barat", postalCode: "16911" },
  { city: "Kota Depok", province: "Jawa Barat", postalCode: "16411" },
  { city: "Kota Tangerang", province: "Banten", postalCode: "15111" },
  { city: "Kota Tangerang Selatan", province: "Banten", postalCode: "15310" },
  { city: "Kabupaten Tangerang", province: "Banten", postalCode: "15710" },
  { city: "Kota Bandung", province: "Jawa Barat", postalCode: "40111" },
  { city: "Kabupaten Bandung", province: "Jawa Barat", postalCode: "40911" },
  { city: "Kota Semarang", province: "Jawa Tengah", postalCode: "50111" },
  { city: "Kota Yogyakarta", province: "DI Yogyakarta", postalCode: "55111" },
  { city: "Kota Surabaya", province: "Jawa Timur", postalCode: "60111" },
  { city: "Kota Denpasar", province: "Bali", postalCode: "80111" },
  { city: "Kota Medan", province: "Sumatera Utara", postalCode: "20111" },
  { city: "Kota Palembang", province: "Sumatera Selatan", postalCode: "30111" },
  { city: "Kota Makassar", province: "Sulawesi Selatan", postalCode: "90111" }
];
